-- Copyright 2018 herd-mdl contributors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
INSERT INTO cnfgn (cnfgn_key_nm, cnfgn_value_ds, cnfgn_value_cl) VALUES ('security.enabled.spel.expression','#request.getHeader("memberOf") != null', NULL);

INSERT INTO scrty_role(
	scrty_role_cd, scrty_role_ds, creat_ts, creat_user_id, updt_ts, updt_user_id)
	VALUES ('sec', 'sec', current_timestamp, 'system', current_timestamp, 'system');
INSERT INTO scrty_role(
	scrty_role_cd, scrty_role_ds, creat_ts, creat_user_id, updt_ts, updt_user_id)
	VALUES ('People', 'People', current_timestamp, 'system', current_timestamp, 'system');


INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 1 ,'sec','FN_BUSINESS_OBJECT_DATA_NOTIFICATION_REGISTRATIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 2 ,'sec','FN_CUSTOM_DDLS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 3 ,'sec','FN_CUSTOM_DDLS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 4 ,'sec','FN_PARTITION_KEY_GROUPS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 5 ,'sec','FN_PARTITION_KEY_GROUPS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 6 ,'sec','FN_STORAGE_PLATFORMS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 7 ,'sec','FN_STORAGE_PLATFORMS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 8 ,'sec','FN_STORAGES_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 9 ,'sec','FN_EXPECTED_PARTITION_VALUES_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 10 ,'sec','FN_EMR_CLUSTER_DEFINITIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 11 ,'sec','FN_EMR_CLUSTERS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 12 ,'sec','FN_JOB_DEFINITIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 13 ,'sec','FN_JOBS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 14 ,'sec','FN_BUILD_INFO_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 15 ,'sec','FN_FILE_TYPES_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 16 ,'sec','FN_STORAGES_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 17 ,'sec','FN_BUSINESS_OBJECT_DATA_GENERATE_DDL_COLLECTION_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 18 ,'sec','FN_BUSINESS_OBJECT_DATA_AVAILABILITY_COLLECTION_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 19 ,'sec','FN_BUSINESS_OBJECT_DATA_STATUS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 20 ,'sec','FN_BUSINESS_OBJECT_DATA_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 21 ,'sec','FN_BUSINESS_OBJECT_DATA_VERSIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 22 ,'sec','FN_BUSINESS_OBJECT_DATA_AVAILABILITY_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 23 ,'sec','FN_BUSINESS_OBJECT_DATA_GENERATE_DDL_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 24 ,'sec','FN_BUSINESS_OBJECT_DATA_S3_KEY_PREFIX_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 25 ,'sec','FN_BUSINESS_OBJECT_DATA_ATTRIBUTES_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 26 ,'sec','FN_BUSINESS_OBJECT_DATA_ATTRIBUTES_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 27 ,'sec','FN_BUSINESS_OBJECT_FORMATS_GENERATE_DDL_COLLECTION_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 28 ,'sec','FN_JOBS_GET_BY_ID' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 29 ,'sec','FN_DOWNLOAD_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 30 ,'sec','FN_STORAGE_POLICIES_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 31 ,'sec','FN_DATA_PROVIDERS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 32 ,'sec','FN_DATA_PROVIDERS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 33 ,'sec','FN_BUSINESS_OBJECT_DATA_NOTIFICATION_REGISTRATIONS_BY_NAMESPACE_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 34 ,'sec','FN_BUSINESS_OBJECT_DATA_NOTIFICATION_REGISTRATIONS_BY_NOTIFICATION_FILTER_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 35 ,'sec','FN_EMR_CLUSTER_DEFINITIONS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 36 ,'sec','FN_BUSINESS_OBJECT_DATA_BY_BUSINESS_OBJECT_DEFINITION_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 37 ,'sec','FN_BUSINESS_OBJECT_DATA_BY_BUSINESS_OBJECT_FORMAT_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 38 ,'sec','FN_BUSINESS_OBJECT_DATA_SEARCH_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 39 ,'sec','FN_STORAGE_UNIT_NOTIFICATION_REGISTRATIONS_BY_NAMESPACE_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 40 ,'sec','FN_STORAGE_UNIT_NOTIFICATION_REGISTRATIONS_BY_NOTIFICATION_FILTER_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 41 ,'sec','FN_STORAGE_UNIT_NOTIFICATION_REGISTRATIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 42 ,'sec','FN_ALLOWED_ATTRIBUTE_VALUES_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 43 ,'sec','FN_GLOBAL_ATTRIBUTE_DEFINITIONS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 44 ,'sec','FN_ATTRIBUTE_VALUE_LISTS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 45 ,'sec','FN_ATTRIBUTE_VALUE_LISTS_GET_ALL' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 46 ,'sec','FN_ATTRIBUTE_VALUE_LISTS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 47 ,'sec','FN_ATTRIBUTE_VALUE_LISTS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 48 ,'sec','FN_GLOBAL_ATTRIBUTE_DEFINITIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');





INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 501 ,'People','FN_BUSINESS_OBJECT_DATA_NOTIFICATION_REGISTRATIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 502 ,'People','FN_JOBS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 503 ,'People','FN_CUSTOM_DDLS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 504 ,'People','FN_CUSTOM_DDLS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 505 ,'People','FN_PARTITION_KEY_GROUPS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 506 ,'People','FN_PARTITION_KEY_GROUPS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 507 ,'People','FN_STORAGE_PLATFORMS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 508 ,'People','FN_STORAGE_PLATFORMS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 509 ,'People','FN_STORAGES_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 510 ,'People','FN_EXPECTED_PARTITION_VALUES_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 511 ,'People','FN_EMR_CLUSTER_DEFINITIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 512 ,'People','FN_EMR_CLUSTERS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 513 ,'People','FN_JOB_DEFINITIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 514 ,'People','FN_JOBS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 515 ,'People','FN_BUILD_INFO_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 516 ,'People','FN_SYSTEM_JOBS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 517 ,'People','FN_STORAGES_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 518 ,'People','FN_FILE_TYPES_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 519 ,'People','FN_UPLOAD_EXTEND_CREDENTIALS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 520 ,'People','FN_BUSINESS_OBJECT_DATA_UNREGISTERED_INVALIDATE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 521 ,'People','FN_BUSINESS_OBJECT_DATA_GENERATE_DDL_COLLECTION_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 522 ,'People','FN_BUSINESS_OBJECT_DATA_AVAILABILITY_COLLECTION_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 523 ,'People','FN_BUSINESS_OBJECT_DATA_S3_KEY_PREFIX_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 524 ,'People','FN_BUSINESS_OBJECT_DATA_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 525 ,'People','FN_BUSINESS_OBJECT_DATA_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 526 ,'People','FN_JOBS_SIGNAL_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 527 ,'People','FN_BUSINESS_OBJECT_DATA_STATUS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 528 ,'People','FN_NAMESPACES_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 529 ,'People','FN_NAMESPACES_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 530 ,'People','FN_BUSINESS_OBJECT_DATA_STATUS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 531 ,'People','FN_DOWNLOAD_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 532 ,'People','FN_BUSINESS_OBJECT_DATA_ATTRIBUTES_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 533 ,'People','FN_BUSINESS_OBJECT_DEFINITIONS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 534 ,'People','FN_BUSINESS_OBJECT_DEFINITIONS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 535 ,'People','FN_BUSINESS_OBJECT_DEFINITIONS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 536 ,'People','FN_BUSINESS_OBJECT_DATA_ATTRIBUTES_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 537 ,'People','FN_EXPECTED_PARTITION_VALUES_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 538 ,'People','FN_BUSINESS_OBJECT_FORMATS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 539 ,'People','FN_BUSINESS_OBJECT_FORMATS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 540 ,'People','FN_BUSINESS_OBJECT_FORMATS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 541 ,'People','FN_BUSINESS_OBJECT_DATA_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 542 ,'People','FN_BUSINESS_OBJECT_DATA_VERSIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 543 ,'People','FN_BUSINESS_OBJECT_DATA_AVAILABILITY_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 544 ,'People','FN_BUSINESS_OBJECT_DATA_GENERATE_DDL_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 545 ,'People','FN_BUSINESS_OBJECT_DATA_ATTRIBUTES_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 546 ,'People','FN_USER_NAMESPACE_AUTHORIZATIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 547 ,'People','FN_USER_NAMESPACE_AUTHORIZATIONS_BY_NAMESPACE_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 548 ,'People','FN_USER_NAMESPACE_AUTHORIZATIONS_BY_USERID_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 549 ,'People','FN_USER_NAMESPACE_AUTHORIZATIONS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 550 ,'People','FN_BUSINESS_OBJECT_DATA_SEARCH_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 551 ,'People','FN_BUSINESS_OBJECT_DATA_ATTRIBUTES_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 552 ,'People','FN_BUSINESS_OBJECT_DATA_ATTRIBUTES_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 553 ,'People','FN_BUSINESS_OBJECT_DATA_STORAGES_FILES_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 554 ,'People','FN_BUSINESS_OBJECT_DATA_NOTIFICATION_REGISTRATIONS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 555 ,'People','FN_BUSINESS_OBJECT_DATA_NOTIFICATION_REGISTRATIONS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 556 ,'People','FN_CUSTOM_DDLS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 557 ,'People','FN_CUSTOM_DDLS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 558 ,'People','FN_CUSTOM_DDLS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 559 ,'People','FN_PARTITION_KEY_GROUPS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 560 ,'People','FN_PARTITION_KEY_GROUPS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 561 ,'People','FN_STORAGES_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 562 ,'People','FN_STORAGES_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 563 ,'People','FN_STORAGES_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 564 ,'People','FN_TAG_TYPES_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 565 ,'People','FN_EXPECTED_PARTITION_VALUES_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 566 ,'People','FN_EMR_CLUSTER_DEFINITIONS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 567 ,'People','FN_EMR_CLUSTER_DEFINITIONS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 568 ,'People','FN_EMR_CLUSTER_DEFINITIONS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 569 ,'People','FN_EMR_CLUSTERS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 570 ,'People','FN_EMR_CLUSTERS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 571 ,'People','FN_EMR_SHELL_STEPS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 572 ,'People','FN_EMR_HIVE_STEPS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 573 ,'People','FN_EMR_PIG_STEPS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 574 ,'People','FN_EMR_HADOOP_JAR_STEPS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 575 ,'People','FN_EMR_MASTER_SECURITY_GROUPS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 576 ,'People','FN_JOB_DEFINITIONS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 577 ,'People','FN_JOB_DEFINITIONS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 578 ,'People','FN_JOBS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 579 ,'People','FN_UPLOAD_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 580 ,'People','FN_TAG_TYPES_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 581 ,'People','FN_TAG_TYPES_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 582 ,'People','FN_TAGS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 583 ,'People','FN_BUSINESS_OBJECT_FORMATS_GENERATE_DDL_COLLECTION_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 584 ,'People','FN_BUSINESS_OBJECT_FORMAT_RETENTION_INFORMATION_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 585 ,'People','FN_TAGS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 586 ,'People','FN_TAGS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 587 ,'People','FN_UPLOAD_BUSINESS_OBJECT_DEFINITION_SAMPLE_DATA_FILE_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 588 ,'People','FN_BUSINESS_OBJECT_DATA_RETRY_STORAGE_POLICY_TRANSITION_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 589 ,'People','FN_JOBS_GET_BY_ID' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 590 ,'People','FN_JOBS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 591 ,'People','FN_STORAGE_POLICIES_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 592 ,'People','FN_STORAGE_POLICIES_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 593 ,'People','FN_BUSINESS_OBJECT_DATA_UPLOAD_CREDENTIAL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 594 ,'People','FN_BUSINESS_OBJECT_DATA_DOWNLOAD_CREDENTIAL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 595 ,'People','FN_BUSINESS_OBJECT_DATA_RESTORE_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 596 ,'People','FN_NOTIFICATION_REGISTRATION_STATUS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 597 ,'People','FN_BUSINESS_OBJECT_DATA_NOTIFICATION_REGISTRATIONS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 598 ,'People','FN_DATA_PROVIDERS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 599 ,'People','FN_DATA_PROVIDERS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 600 ,'People','FN_DATA_PROVIDERS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 601 ,'People','FN_DATA_PROVIDERS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 602 ,'People','FN_STORAGE_POLICIES_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 603 ,'People','FN_USER_NAMESPACE_AUTHORIZATIONS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 604 ,'People','FN_USER_NAMESPACE_AUTHORIZATIONS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 605 ,'People','FN_USER_NAMESPACE_AUTHORIZATIONS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 606 ,'People','FN_NAMESPACE_IAM_ROLE_AUTHORIZATIONS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 607 ,'People','FN_NAMESPACE_IAM_ROLE_AUTHORIZATIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 608 ,'People','FN_NAMESPACE_IAM_ROLE_AUTHORIZATIONS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 609 ,'People','FN_NAMESPACE_IAM_ROLE_AUTHORIZATIONS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 610 ,'People','FN_NAMESPACE_IAM_ROLE_AUTHORIZATIONS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 611 ,'People','FN_STORAGE_UNIT_DOWNLOAD_CREDENTIAL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 612 ,'People','FN_STORAGE_UNIT_UPLOAD_CREDENTIAL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 613 ,'People','FN_BUSINESS_OBJECT_DEFINITION_TAGS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 614 ,'People','FN_SEARCH_INDEXES_ACTIVATION_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 615 ,'People','FN_SEARCH_INDEXES_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 616 ,'People','FN_SEARCH_INDEXES_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 617 ,'People','FN_SEARCH_INDEXES_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 618 ,'People','FN_SEARCH_INDEXES_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 619 ,'People','FN_BUSINESS_OBJECT_DATA_STORAGE_UNITS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 620 ,'People','FN_BUSINESS_OBJECT_DATA_NOTIFICATION_REGISTRATIONS_BY_NAMESPACE_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 621 ,'People','FN_BUSINESS_OBJECT_DATA_NOTIFICATION_REGISTRATIONS_BY_NOTIFICATION_FILTER_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 622 ,'People','FN_EMR_CLUSTER_DEFINITIONS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 623 ,'People','FN_BUSINESS_OBJECT_FORMAT_ATTRIBUTE_DEFINITIONS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 624 ,'People','FN_BUSINESS_OBJECT_DATA_ATTRIBUTES_ALL_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 625 ,'People','FN_BUSINESS_OBJECT_DATA_BY_BUSINESS_OBJECT_DEFINITION_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 626 ,'People','FN_BUSINESS_OBJECT_DATA_BY_BUSINESS_OBJECT_FORMAT_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 627 ,'People','FN_BUSINESS_OBJECT_DEFINITION_COLUMNS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 628 ,'People','FN_BUSINESS_OBJECT_DEFINITION_COLUMNS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 629 ,'People','FN_BUSINESS_OBJECT_DEFINITION_COLUMNS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 630 ,'People','FN_STORAGE_UNIT_NOTIFICATION_REGISTRATIONS_BY_NAMESPACE_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 631 ,'People','FN_STORAGE_UNIT_NOTIFICATION_REGISTRATIONS_BY_NOTIFICATION_FILTER_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 632 ,'People','FN_STORAGE_UNIT_NOTIFICATION_REGISTRATIONS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 633 ,'People','FN_STORAGE_UNIT_NOTIFICATION_REGISTRATIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 634 ,'People','FN_STORAGE_UNIT_NOTIFICATION_REGISTRATIONS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 635 ,'People','FN_STORAGE_UNIT_NOTIFICATION_REGISTRATIONS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 636 ,'People','FN_BUSINESS_OBJECT_DATA_DESTROY_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 637 ,'People','FN_BUSINESS_OBJECT_DEFINITIONS_DESCRIPTIVE_INFO_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 638 ,'People','FN_BUSINESS_OBJECT_DEFINITION_SUBJECT_MATTER_EXPERTS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 639 ,'People','FN_BUSINESS_OBJECT_DEFINITION_SUBJECT_MATTER_EXPERTS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 640 ,'People','FN_BUSINESS_OBJECT_FORMAT_PARENTS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 641 ,'People','FN_BUSINESS_OBJECT_DEFINITION_TAGS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 642 ,'People','FN_ALLOWED_ATTRIBUTE_VALUES_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 643 ,'People','FN_ALLOWED_ATTRIBUTE_VALUES_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 644 ,'People','FN_ALLOWED_ATTRIBUTE_VALUES_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 645 ,'People','FN_GLOBAL_ATTRIBUTE_DEFINITIONS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 646 ,'People','FN_GLOBAL_ATTRIBUTE_DEFINITIONS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 647 ,'People','FN_GLOBAL_ATTRIBUTE_DEFINITIONS_ALL_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 648 ,'People','FN_ATTRIBUTE_VALUE_LISTS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 649 ,'People','FN_STORAGE_ATTRIBUTES_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 650 ,'People','FN_ATTRIBUTE_VALUE_LISTS_GET_ALL' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 651 ,'People','FN_ATTRIBUTE_VALUE_LISTS_POST' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 652 ,'People','FN_ATTRIBUTE_VALUE_LISTS_DELETE' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 653 ,'People','FN_GLOBAL_ATTRIBUTE_DEFINITIONS_GET' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 654 ,'People','FN_BUSINESS_OBJECT_FORMAT_ATTRIBUTES_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');
INSERT INTO scrty_role_fn(scrty_role_fn_id, scrty_role_cd, scrty_fn_cd, creat_ts, creat_user_id, updt_ts, updt_user_id) VALUES ( 655 ,'People','FN_BUSINESS_OBJECT_DATA_STORAGE_UNIT_STATUS_PUT' ,current_timestamp, 'system' ,current_timestamp, 'system');


